# Generated by Django 4.2.10 on 2024-04-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='type_event',
            field=models.CharField(choices=[('online', 'онлайн'), ('online+offline', 'онлайн+оффлайн')], max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='type_event',
            field=models.CharField(choices=[('online', 'онлайн'), ('online+offline', 'онлайн+оффлайн')], max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type_event',
            field=models.CharField(choices=[('online', 'онлайн'), ('online+offline', 'онлайн+оффлайн')], max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('future', 'будущие'), ('current', 'текущие (идет эфир)'), ('completed', 'завершенные')], max_length=50, verbose_name='Статус мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('online', 'онлайн'), ('online+offline', 'онлайн+оффлайн')], max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type_event',
            field=models.CharField(choices=[('online', 'онлайн'), ('online+offline', 'онлайн+оффлайн')], max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='events.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_favorite_recipe'),
        ),
    ]
