# Generated by Django 4.2.10 on 2024-04-15 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='event',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.adress', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='event',
            name='broadcast',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.broadcast', verbose_name='Трансляция'),
        ),
        migrations.AddField(
            model_name='event',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='event',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.questionnaire', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.city', verbose_name='Город'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_favorite_recipe'),
        ),
    ]
