# Generated by Django 4.2.10 on 2024-04-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='event',
            name='broadcast',
        ),
        migrations.RemoveField(
            model_name='event',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='questionnaire',
        ),
    ]
