# Generated by Django 4.2.10 on 2024-04-14 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_adress_type_event_alter_broadcast_type_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('online', 'онлайн'), ('online+offline', 'онлайн+оффлайн')], default=django.utils.timezone.now, max_length=50, verbose_name='Тема мероприятия'),
            preserve_default=False,
        ),
    ]
