# Generated by Django 4.2.10 on 2024-04-15 13:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('firstName', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='Телефон')),
                ('interest', models.CharField(blank=True, choices=[('Backend', 'Backend'), ('IOS', 'IOS'), ('Android', 'Android'), ('UI/UX дизайн', 'UI/UX дизайн')], max_length=255, null=True, verbose_name='Интересы')),
                ('notificationByTelegram', models.BooleanField(blank=True, null=True)),
                ('notificationByWhatsapp', models.BooleanField(blank=True, null=True)),
                ('notificationByVk', models.BooleanField(blank=True, null=True)),
                ('notificationByViber', models.BooleanField(blank=True, null=True)),
                ('telegram', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('vk', models.CharField(blank=True, max_length=20, null=True)),
                ('viber', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities_events', to='events.event')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='selected_events_events', to='events.event')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='selected_events_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedActivities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.event')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.useractivities')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
